mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('visual.urls', namespace='visual')),
]

visual/urls.py
from django.urls import path
from . import views

app_name = 'visual'

urlpatterns = [
    # post views
    path('', views.draw_map, name='draw_map'),
    path('popup',views.popup,name='popup'),
    path('filter_by_year',views.filter_by_year,name='filter_by_year'),
    path('open_popup_window',views.open_popup_window,name='opened_popup_window'),
]

visual/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
import datetime

def year_choices():
    return [(r,r) for r in range(1984, datetime.date.today().year+1)]

def current_year():
    return datetime.date.today().year

def game_stage_choices():
    return [('Group','Group'),('Round of 16','Round of 16'),('Quarter','Quarter'),('Semis','Semis')]
# Create your models here.
class Stadium(models.Model):
    #objects = models.Manager()
    name = models.CharField(max_length=100)
    lat = models.FloatField()
    long = models.FloatField()
    #world_cup_year = models.DateField(default='2018-06-14')
    year = models.IntegerField(('year'), choices=year_choices(), default=current_year())

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class Game(models.Model):
    stadium = models.ForeignKey(Stadium, on_delete=models.CASCADE,
                                related_name='games', default='9999')
    objects = models.Manager()
    team_a = models.CharField(max_length=50)
    team_b = models.CharField(max_length=50)
    score = models.CharField(max_length=5,default='0-0')
    stage = models.CharField(max_length=20,choices=game_stage_choices(),default='Group')
    game_date = models.DateField()


    class Meta:
        ordering = ('game_date',)

    def __str__(self):
        return '{} vs {}'.format(self.team_a, self.team_b)

visual/views.py
from django.shortcuts import render
from .models import Stadium, Game
from django.http import HttpResponse
from django.http import JsonResponse
import json
# Create your views here.

def draw_map(request):
    #stadiums = Stadium.objects.all()
    #return render(request,'map/plot_map.html',{'stadiums':stadiums})
    return render(request, 'map/plot_map.html')


def filter_by_year(request):
    if request.method == 'GET':
        stadiums = Stadium.objects.filter(year=request.GET['data']).values()
        return JsonResponse({'dj_data':list(stadiums)})


def popup(request):
    if request.method == 'GET':
        if request.GET.get('stadium_name', 0) != 0:
            games = Game.objects.filter(stadium__name=request.GET['stadium_name']).values()
            print(games)
            return JsonResponse({'games_played': list(games)})

        obj = json.loads(request.GET['d'])
        for i in range(len(obj['dj_data'])):
            obj['dj_data'][i]['number_of_games'] = len(Game.objects.filter(stadium__name=str(obj['dj_data'][i]['name'])))
        return JsonResponse(obj)

def open_popup_window(request):
    return render(request,'map/popup.html')

visual/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'leaflet.css' %}" rel="stylesheet">
    <script src="{% static 'leaflet.js' %}"></script>
</head>
<body>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
<div id="map"></div>
</body>
</html>

visual/templates/map/plot_map.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>Visualization</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

<link href="{% static 'layout/styles/layout.css' %}" rel="stylesheet" type="text/css" media="all">
<link href="{% static 'dropdown.css' %}" rel="stylesheet">

<!--------------------------------------------->
<title>A Leaflet map!</title>
<link href="{% static 'leaflet/leaflet.css' %}" rel="stylesheet">
  <script src="{% static 'leaflet/leaflet.js' %}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<style>
  #map{ height: 560px; width: 1133px;}
</style>
<!--------------------------------------------->
</head>
<body id="top">
<div class="wrapper row1">
  <header id="header" class="hoc clear">
    <div id="logo" class="fl_left">
      <h1><a href="">Soccer</a></h1>
    </div>
    <nav id="mainav" class="fl_right">
      <ul class="clear">
        <li class="active"><a href="">Home</a></li>
        <li><a href="/admin">Admin</a></li>
      </ul>
    </nav>
  </header>
</div>
<div id="map"></div>
<div id="sidebar_home_right">
  <span class="custom-dropdown">
          <select id="sources" class="selectYear">
              <option selected disabled>Select World Cup Year</option>
              <option value="2018">2018</option>
              <option value="2014">2014</option>
          </select>
      </span>
</div>
<style>
#sidebar_home_right {
    background-image: url("static/images/messi.jpg");
    background-color: #cccccc;
    background-position: -80% 0;
    position: absolute;
    left:1133px;
    top:99px;
    width:1133px;
    height: 560px;
}

</style>

<script>
  function openWindow(name){
    var popupWindow = window.open("open_popup_window", "MsgWindow", "top=100, left=200, width=800, height=500");
    url = "{% url "visual:popup" %}";

    $.get(url, { d: name, stadium_name: name } )
      .done(function(data){
        popupWindow.window.onload = function() {

                    for(i=0;i<data['games_played'].length;i++){
                        var tr = document.createElement("tr");

                        var td = document.createElement('td');
                        var td_text = document.createTextNode(data['games_played'][i]['team_a']);
                        td.appendChild(td_text);
                        tr.appendChild(td);

                        var td = document.createElement('td');
                        var td_text = document.createTextNode(data['games_played'][i]['team_b']);
                        td.appendChild(td_text);
                        tr.appendChild(td);

                        var td = document.createElement('td');
                        var td_text = document.createTextNode(data['games_played'][i]['score']);
                        td.appendChild(td_text);
                        tr.appendChild(td);

                        var td = document.createElement('td');
                        var td_text = document.createTextNode(data['games_played'][i]['stage']);
                        td.appendChild(td_text);
                        tr.appendChild(td);


                        popupWindow.document.getElementById('game_list').appendChild(tr);
                    }
                }
      });

  }
  var markers = new Array();
  function plotPoints(){
        url = "{% url "visual:filter_by_year" %}";
        var code = $("#sources option:selected").val();

        var markerIcon = L.icon({
        iconUrl: '{% static "leaflet/images/marker-icon.png" %}',
        shadowUrl: '{% static "leaflet/images/marker-shadow.png" %}',
        iconSize:     [25, 41],
        iconAnchor:   [12,36],
        });
        $.get(url, { data: code} )
            .done(function(data){
              try{
                for(i=0;i<markers.length;i++) {
                  map.removeLayer(markers[i]);
                }
                markers.splice(0,markers.length);
            }catch(err){
                //pass
              }
              $.get("/popup",{d:JSON.stringify(data)}).done(function(data){
                for(i=0;i<data['dj_data'].length;i++){
                  marker = L.marker([data['dj_data'][i].lat, data['dj_data'][i].long],{icon:markerIcon}).addTo(map);

                  var div = document.createElement("div");
                  div.innerHTML = data['dj_data'][i].name + '<br>' +
                  'Total Games Played: '+data['dj_data'][i].number_of_games + '<br><a href=\'#\' onclick="openWindow(\''+data['dj_data'][i].name+'\')">more info!!</a>';
                  marker.bindPopup(div);
                  markers.push(marker);
                }
                map.panTo(new L.LatLng(data['dj_data'][0].lat, data['dj_data'][0].long));
              });
    });
  }
  function callFunctions(){
        $.when( plotPoints() ).done(function() {
        });
  }
  $( "select.selectYear" ).change(callFunctions);


  // initialize the map
  var map = L.map('map').setView([55.7093305, 37.55216446], 3);


  L.tileLayer('http://{s}.tiles.wmflabs.org/bw-mapnik/{z}/{x}/{y}.png', {
    maxZoom: 19,
    minZoom: 3,
    attribution: "&copy; <a href='http://www.openstreetmap.org/copyright'>OpenStreetMap</a>"
  }).addTo(map);
</script>

<!-- JAVASCRIPTS-->

<script src="{% static 'layout/scripts/jquery.backtotop.js' %}"></script>
<script src="{% static 'layout/scripts/jquery.min.js' %}"></script>
<script src="{% static 'layout/scripts/jquery.mobilemenu.js' %}"></script>

</body>
</html>

visual/templates/map/popup.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Games List</title>
	<link href="{% static 'popup.css' %}" rel="stylesheet">
</head>
<body>
  <div class="container">
	<table >
		<thead>
			<tr>
				<th>Team A</th>
				<th>Team B</th>
				<th>Score</th>
				<th>Stage</th>
			</tr>
		</thead>
		<tbody id="game_list">

		</tbody>
	</table>
</div>
</body>
</html>